# Application
quarkus.application.name=datanest
quarkus.http.port=38799

quarkus.index-dependency.core.group-id=io.kneo
quarkus.index-dependency.officeframe.group-id=io.kneo

# Suppress verbose FFmpeg wrapper output
quarkus.log.category."net.bramp.ffmpeg".level=WARN
quarkus.log.category."net.bramp.ffmpeg.builder".level=ERROR
quarkus.log.category."net.bramp.ffmpeg.RunProcessFunction".level=ERROR
